/**
 * This code generated by CodeGenerator<283241292@qq.com>
 */
package com.cp.mybatis.bean;

/**
 * <p>实体类</p>
 * <p>Table: loan_switch_config - 放款开关配置表 -创建人：陈鹏</p>
 *
 * @since 2019-06-09 02:54:19
 */
public class LoanSwitchConfig{

	/** id - 主键id */
	private Long id;
	/** app_name - APP平台 21-Aku Cepat */
	private Integer appName;
	/** switch_status - 开关状态：1开 2关 */
	private Integer switchStatus;
	/** create_time - 创建时间 */
//	private String createTime;
	/** create_man - 创建人 */
	private String createMan;
	/** update_time - 更新时间 */
//	private String updateTime;
	/** update_man - 更新人 */
	private String updateMan;
	/** remark - 备注 */
	private String remark;

	public LoanSwitchConfig() {
	}

	public LoanSwitchConfig(Long id, Integer appName, Integer switchStatus, String createMan, String updateMan, String remark) {
		this.id = id;
		this.appName = appName;
		this.switchStatus = switchStatus;
		this.createMan = createMan;
		this.updateMan = updateMan;
		this.remark = remark;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getAppName() {
		return appName;
	}

	public void setAppName(Integer appName) {
		this.appName = appName;
	}

	public Integer getSwitchStatus() {
		return switchStatus;
	}

	public void setSwitchStatus(Integer switchStatus) {
		this.switchStatus = switchStatus;
	}

	public String getCreateMan() {
		return createMan;
	}

	public void setCreateMan(String createMan) {
		this.createMan = createMan;
	}

	public String getUpdateMan() {
		return updateMan;
	}

	public void setUpdateMan(String updateMan) {
		this.updateMan = updateMan;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Override
	public String toString() {
		return "LoanSwitchConfig{" +
				"id=" + id +
				", appName=" + appName +
				", switchStatus=" + switchStatus +
				", createMan='" + createMan + '\'' +
				", updateMan='" + updateMan + '\'' +
				", remark='" + remark + '\'' +
				'}';
	}
}